version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    image: golang_image
    container_name: golangContainer
    volumes:
      - ./:/app
    network_mode: bridge



